trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - builds/android-ci.yml
    - TVST.Android*/**
    - misc/**
pool:
  vmImage: 'macos-15'

variables:
  buildConfiguration: 'Release'


steps:
- task: Bash@3
  displayName: 'Update Build Number'
  inputs:
    targetType: 'inline'
    script: |
      # Create new build number with timestamp base
      newBuildNumber=$(date +%Y%m%d%H%M)    
      echo "##vso[task.setvariable variable=NEW_BUILD_NUMBER]$newBuildNumber"

      # Update the pipeline build number
      finalBuildNumber="$(Build.BuildNumber) • Build $newBuildNumber"
      echo "##vso[build.updatebuildnumber]$finalBuildNumber"
  condition: always()

- task: Bash@3
  displayName: 'Force version of XCODE'
  inputs:
    targetType: 'inline'
    script: |
      echo "Versions de Xcode utilisée avant:"
      xcodebuild -version
      # Vérifier les versions de Xcode disponibles
      echo "Versions de Xcode disponibles:"
      ls -la /Applications/ | grep Xcode
      
      # Utiliser une version plus récente de Xcode si disponible
      sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
      
      # Vérifier la version active de Xcode
      echo "Versions de Xcode utilisée après:"
      xcodebuild -version

- task: Bash@3
  displayName: 'Install dotnet maui-ios workload'
  inputs:
    targetType: 'inline'
    script: 'dotnet workload install maui-ios'

- task: DotNetCoreCLI@2
  displayName: 'Restore nugets'
  inputs:
    command: 'restore'
    projects: '$(projectName)/*.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    
- task: DotNetCoreCLI@2
  displayName: 'Pack nuget package'
  inputs:
    command: 'pack'
    projects: '$(projectName)/*.csproj'
    arguments: '-c $(buildConfiguration)'
