name: NuGet Package Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs'
jobs:
  build:
    runs-on: macos-latest
    
    env:
      buildConfiguration: 'Release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Update Build Number
        id: build-number
        run: |
          # Create new build number with timestamp base
          newBuildNumber=$(date +%Y%m%d%H%M)
          echo "NEW_BUILD_NUMBER=$newBuildNumber" >> $GITHUB_ENV
          echo "Build number: $newBuildNumber"
        shell: bash

      - name: Force version of Xcode
        run: |
          echo "Versions de Xcode utilisée avant:"
          xcodebuild -version
          
          echo "Versions de Xcode disponibles:"
          ls -la /Applications/ | grep Xcode
          
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          
          echo "Versions de Xcode utilisée après:"
          xcodebuild -version
        shell: bash

      - name: Install dotnet maui-ios workload
        run: dotnet workload install maui-ios
        shell: bash

      - name: Restore NuGet packages
        run: dotnet restore src\Plugin.InAppBilling/*.csproj

      - name: Pack NuGet package
        run: dotnet pack src\Plugin.InAppBilling/*.csproj -c ${{ env.buildConfiguration }}

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src\Plugin.InAppBilling/bin/${{ env.buildConfiguration }}/*.nupkg