name: NuGet Package Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs'
jobs:
  build:
    runs-on: macos-latest
    
    env:
      buildConfiguration: 'Release'
      SRC_FOLDER: ./src/
      PROJ_NAME: Plugin.InAppBilling

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Update Build Number
        id: build-number
        run: |
          # Create new build number with timestamp base
          newBuildNumber=$(date +%Y%m%d%H%M)
          echo "NEW_BUILD_NUMBER=$newBuildNumber" >> $GITHUB_ENV
          echo "Build number: $newBuildNumber"
        shell: bash

      - name: Force version of Xcode
        run: |
          echo "Versions of Xcode before:"
          xcodebuild -version
          
          echo "Available versions of Xcode:"
          ls -la /Applications/ | grep Xcode
          
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          
          echo "Versions of Xcode after:"
          xcodebuild -version
        shell: bash

      - name: Install dotnet maui-ios and maui-android workloads
        run: dotnet workload install maui-ios maui-android
        shell: bash

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.SRC_FOLDER }}${{ env.PROJ_NAME }}/${{ env.PROJ_NAME }}.csproj
        
      - name: Build project
        run: dotnet build ${{ env.SRC_FOLDER }}${{ env.PROJ_NAME }}/${{ env.PROJ_NAME }}.csproj -c ${{ env.buildConfiguration }}

      - name: Pack as NuGet package
        run: dotnet pack ${{ env.SRC_FOLDER }}${{ env.PROJ_NAME }}/${{ env.PROJ_NAME }}.csproj -c ${{ env.buildConfiguration }}

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.SRC_FOLDER }}${{ env.PROJ_NAME }}/bin/${{ env.buildConfiguration }}/*.nupkg